/** The application code
 * This is called from the CubeMX generated main() function after all initialization has completed */

#include <stdio.h>
#include <stdbool.h>

#include "stm32l4xx_hal.h"

#include "debug.h"
#include "modem_at.h"
#include "modem_ll.h"
#include "app_iwdg.h"
#include "led.h"
#include "app.h"

// TODO: configuration data
static const char *APN = "TM";
static const char *HTP_HOSTS[] = {"www.google.com", "www.cloudflare.com", "aws.amazon.com", "www.microsoft.com"};

// private forward declarations
static bool ModemServiceUp (void);
static bool ModemServiceDown (void);
static void WatchdogCallback (void);

/**
 * @brief the main application, called from the main function that is
 *        generated by CubeMX */
void App (void) {
#if DEBUG >= 1
	printf ("\r\nBoat Environment Monitor starting\r\n");
	printf ("App: Setting up modem\r\n");
#endif

	// bring up the modem
	bool modem_service_up = ModemServiceUp ();

	// even if the modem isn't available, it may still be possible to read its real-time clock
	time_t rtc_time;
	bool status = ModemGetRTCTime (&rtc_time, 3);
	// if the real-time clock is within a year of the start of the epoch, assume it
	// has never been set, and so isn't usable
	bool clock_valid = true;
	if (rtc_time < (86400 * 365))
		clock_valid = false;


#if DEBUG >= 1
	printf ("App: Bringing down modem\r\n");
#endif
    status = ModemServiceDown ();
	if (! status)
		modem_service_up = false;

#if DEBUG >= 1
	printf ("App: Program finished, status: clock=%s; modem_service=%s\r\n",
	        clock_valid ? "valid" : "not valid",
	        modem_service_up ? "up" : "not up");
#endif
	// work out what to display on the LED
	LEDPattern_t pattern;
	if (! clock_valid) pattern = LED_CLOCK_ERROR;
	else if (! modem_service_up) pattern = LED_MODEM_ERROR;
	else pattern = LED_SUCCESS;
	BlinkLEDForever (pattern, WatchdogCallback);	
}

/**
 * @brief start the Modem service
 */
static bool ModemServiceUp (void) {
	// Setup modem comms
	ModemStart (WatchdogCallback);

	// Modem setup...
	bool modem_status = false;
	for (int n_retries = 0; (n_retries < 3) && (! modem_status); n_retries ++) {
		// reset after previous attempts
		if (n_retries > 0) {
            ModemLLReset ();
		}

		// check comms to the modem
		modem_status = ModemTestComms (3);
	
		// Check the modem is in full functionality mode
		if (modem_status)
			modem_status = ModemCheckFullFunctionality (3);

		// check the SIM is ready
		if (modem_status)
			modem_status = ModemCheckSIMReady (5);

		// check that the modem is in automatic operator selection mode
		if (modem_status)
			modem_status = ModemCheckAutoOperSelMode (3);

		// check that the modem is registered with the mobile network
		if (modem_status)
			modem_status = ModemCheckRegistered (10);

		// check the received signal strength (mainly of interest for debugging, but would
		// be useful if it could be communicated in normal use, as it would show when the
		// modem is out of range from a cell tower)
		int rssi = 999;
		if (modem_status) {
			rssi = ModemGetSignalStrength ();
			if (rssi == 999)
				modem_status = false;
		}
		
		// bring up the modem's internet stack
		if (modem_status)
			modem_status = ModemCheckIPOpened (APN, 3);
			
		// update the modem's real-time-clock from the network
		if (modem_status)
			modem_status = ModemSyncToHTPTime (HTP_HOSTS, sizeof(HTP_HOSTS) / sizeof(HTP_HOSTS[0]), 3);
	}
	return modem_status;
}

/**
 * @brief stop the Modem service
 */
static bool ModemServiceDown (void) {
	// bring down modem ...
	bool modem_status = false;
	for (int n_retries = 0; (n_retries < 3) && (! modem_status); n_retries ++) {
		// bring down the modem's internet stack
		modem_status = ModemCheckIPClosed (3);
	}
	ModemStop ();

	return modem_status;
}

/**
 * @brief an error handler reference by CubeMX error handlers
 */
void AppError (void) {
#if DEBUG >= 1
	printf ("App error handler called\r\n");
#endif

	BlinkLEDForever (LED_SYSTEM_ERROR, WatchdogCallback);
}

/**
 * @brief a callback that prevents HAL's watchdog from restarting the applications
 */
static void WatchdogCallback (void) {
	PingIWDG ();
}
	
